repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: nginx
    chart: ingress-nginx/ingress-nginx
    version: 2.7.0
    values:
      - controller:
          metrics:
            port: 10254
            # if this port is changed, change healthz-port: in extraArgs: accordingly
            enabled: true
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"