# Default values for istio-bookinfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

detailsv1:
  image:
    repository: istio/examples-bookinfo-details-v1
    tag: 1.15.0

productpagev1:
  image:
    repository: istio/examples-bookinfo-productpage-v1
    tag: 1.15.0

ratingsv1:
  image:
    repository: istio/examples-bookinfo-ratings-v1
    tag: 1.15.0

reviewsv1:
  image:
    repository: istio/examples-bookinfo-reviews-v1
    tag: 1.15.0

reviewsv2:
  image:
    repository: istio/examples-bookinfo-reviews-v2
    tag: 1.15.0

reviewsv3:
  image:
    repository: istio/examples-bookinfo-reviews-v3
    tag: 1.15.0


gateway:
  selector: ingressgateway
  hostname: example.com

  httpsRedirect: false

  tls:
    enabled: false
    secretName: bookinfo-tls
    gatewayNamespace: istio-system
    acme:
      enabled: false
      certManager:
        version: certmanager.k8s.io/v1alpha1
      renewBefore: 720h
      issuerName: letsencrypt
      issuerKind: ClusterIssuer
