apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "command-trigger.fullname" . }}
  labels:
{{ include "command-trigger.labels" . | indent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "command-trigger.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: {{ include "command-trigger.image" . }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/bash
              args:
                - -c
                - {{ .Values.command | quote }}
          restartPolicy: {{ .Values.restartPolicy }}
