{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ping.fullname" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ping.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ping.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
