---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "usercount.fullname" . }}
data:
  prometheus.yml: |
    global:
      scrape_interval:     10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'usercount'
        static_configs:
        - targets: ['{{ include "usercount.fullname" . }}-usercount:9100']
