---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usercount.fullname" . }}-usercount
  labels:
    {{- include "usercount.usercount.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "usercount.usercount.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        {{- include "usercount.usercount.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ include "usercount.usercount.image" . }}
        name: usercount
        ports:
        - containerPort: 9100
          name: http
          protocol: TCP
