---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-go-app.fullname" . }}-hashbrowns
  labels:
    {{- include "example-go-app.hashbrowns.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    {{- include "example-go-app.hashbrowns.selectorLabels" . | nindent 4}}
