---
apiVersion: v1
kind: ConfigMap
data:
  traefik.toml: |
    debug = false
    InsecureSkipVerify = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoint.traefik]
      address = ":8080"
      [entryPoint.dashboard]
      address = "localhost:8081"
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.auth.basic]
      users = ["sysdig:$apr1$uQbLhzdg$rL1kSym5BYd1oc.KHjkwm0"]
      removeHeader = true
      [entryPoints.https.tls]
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]
    [api]
    dashboard = true
    entryPoint = "dashboard"
    debug = true
    [acme]
    email = "some@email.com"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
    [acme.httpChallenge]
    entryPoint = "http"
    [[acme.domains]]
    main = "traefik.example-domain.com"
metadata:
  name: traefik-conf
