# Default values for command-trigger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: debian
  tag: buster
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

schedule: "0 6 * * *"
failedJobsHistoryLimit: 5
successfulJobsHistoryLimit: 2
restartPolicy: Never

command: 'echo "HelloWorld!"'
