---
apiVersion: v1
data:
  README.md: |-
    You can copy here your custom `.sh`, `.sql` or `.sql.gz` file so they are executed during the first boot of the image.

    More info in the [bitnami-docker-postgresql](https://github.com/bitnami/bitnami-docker-postgresql#initializing-a-new-instance) repository.
kind: ConfigMap
metadata:
  labels:
    app: postgresql
    chart: postgresql-3.1.3
    heritage: Tiller
    release: pg-database
  name: pg-database-postgresql-init-scripts
