---
apiVersion: v1
data:
  postgresql-password: N0d0dE4yUDVIMw==
  postgresql-replication-password: cmVwbF9wYXNzd29yZA==
kind: Secret
metadata:
  labels:
    app: postgresql
    chart: postgresql-3.1.3
    heritage: Tiller
    release: pg-database
  name: pg-database-postgresql
type: Opaque
