---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "example-java-app.fullname" . }}-redis
  labels:
        {{- include "example-java-app.redis.labels" . | nindent 4 }}
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    matchLabels:
        {{- include "example-java-app.redis.selectorLabels" . | nindent 6 }}
  template:
    spec:
      securityContext:
        runAsUser: 0
      serviceAccountName: {{ include "example-java-app.fullname" . }}
      containers:
      - name: redis
        image: {{ include "example-java-app.redis.image" . }}
        ports:
        - containerPort: 6379
          name: redis
        command: [ "redis-server", "--appendonly", "yes" ]
        resources:
{{ toYaml .Values.redis.resources | indent 10 }}
    metadata:
      labels:
        {{- include "example-java-app.redis.selectorLabels" . | nindent 8 }}
