---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "example-java-app.fullname" . }}-cassandra
  labels:
        {{- include "example-java-app.cassandra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
        {{- include "example-java-app.cassandra.selectorLabels" . | nindent 6}}
  template:
    spec:
      securityContext:
        runAsUser: 0
      serviceAccountName: {{ include "example-java-app.fullname" . }}
      containers:
      - name: cassandra
        image: {{ include "example-java-app.cassandra.image" . }}
        ports:
        - containerPort: 9042
          name: cassandra
        - containerPort: 9160
          name: thrift-client
        - containerPort: 7000
          name: internode
        - containerPort: 7001
          name: internode-ssl
        - containerPort: 7199
          name: jmx
        resources:
{{ toYaml .Values.cassandra.resources | indent 10 }}
    metadata:
      labels:
        {{- include "example-java-app.cassandra.selectorLabels" . | nindent 8}}
