---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-java-app.fullname" . }}-mongo
  labels:
        {{- include "example-java-app.mongo.labels" . | nindent 4 }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
        {{- include "example-java-app.mongo.selectorLabels" . | nindent 4 }}
