---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-java-app.fullname" . }}-javaapp
  labels:
        {{- include "example-java-app.javaapp.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
        {{- include "example-java-app.javaapp.selectorLabels" . | nindent 4 }}
