kind: .
metadata:
  name: .
spec: 
  template:
    spec:
      containers:
      - name: main 
        securityContext:
          allowPrivilegeEscalation: false
      initContainers:
      - name: register 
        securityContext:
          allowPrivilegeEscalation: false
