apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yace-exporter.fullname" . }}-config
  labels:
    {{- include "yace-exporter.common.labels" . | nindent 4 }}
    {{- include "yace-exporter.labels" . | nindent 4 }}
data:
  config.yml: |
    discovery:
{{ toYaml .Values.discovery | indent 6 }}
