apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yace-exporter.fullname" . }}-credentials
  labels:
    {{- include "yace-exporter.common.labels" . | nindent 4 }}
    {{- include "yace-exporter.labels" . | nindent 4 }}
data:
  # Expose AWS in credentials the the env var:
  # AWS_CREDENTIALS=$(cat ~/.aws/credentials | base64)
  credentials: |
{{ .Values.awsCredentials | indent 4 }}
