apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sock-shop.fullname" . }}-orders
  labels:
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    {{- include "sock-shop.orders.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sock-shop.orders.labels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "sock-shop.common.labels" . | nindent 8 }}
        {{- include "sock-shop.orders.labels" . | nindent 8 }}
{{ if .Values.orders.prometheus.active }}
      annotations:
        {{- include "sock-shop.orders.annotations" . | nindent 8 }}
{{ end }}
    spec:
      serviceAccountName: {{ template "sock-shop.serviceAccountName" .}}
      containers:
      - name: orders
        image: {{ include "sock-shop.orders.image" . }}
        env:
         - name: JAVA_OPTS
           value: -Xms64m -Xmx350m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
        ports:
        - containerPort: 80
        resources:
{{ toYaml .Values.orders.resources | indent 10 }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
