apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sock-shop.fullname" . }}-front-end
  labels:
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    {{- include "sock-shop.front-end.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sock-shop.front-end.labels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "sock-shop.common.labels" . | nindent 8 }}
        {{- include "sock-shop.front-end.labels" . | nindent 8 }}
{{ if .Values.frontend.prometheus.active }}
      annotations:
        {{- include "sock-shop.front-end.annotations" . | nindent 8 }}
{{ end }}
    spec:
      serviceAccountName: {{ template "sock-shop.serviceAccountName" .}}
      containers:
      - name: front-end
        image: {{ include "sock-shop.front-end.image" . }}
        ports:
        - containerPort: 8079
        resources:
{{ toYaml .Values.frontend.resources | indent 10 }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
