apiVersion: v1
kind: Service
metadata:
  name: carts-db
  labels:
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    {{- include "sock-shop.carts-db.labels" . | nindent 4 }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    {{- include "sock-shop.carts-db.labels" . | nindent 4 }}