apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    {{- include "sock-shop.shipping.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    {{- include "sock-shop.shipping.labels" . | nindent 4 }}