apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  labels:
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    {{- include "sock-shop.catalogue-db.labels" . | nindent 4 }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    {{- include "sock-shop.catalogue-db.labels" . | nindent 4 }}