resources:
- all.yaml
patches:
- path: ./patches/1686760433_remediate_SecurityContext_runAsUser_for_workload_calico-node.yaml
  target:
    kind: DaemonSet
    name: calico-node
    namespace: kube-system
