resources:
- all.yaml
patches:
- path: ./patches/1690377520_remediate_SecurityContext_allowPrivilegeEscalation_for_workload_calico-node.yaml
  target:
    kind: DaemonSet
    name: calico-node
    namespace: kube-system
