resources:
- all.yaml
patches:
- path: ./patches/1692140602_remediate_SecurityContext_readOnlyRootFilesystem_for_workload_calico-node.yaml
  target:
    kind: DaemonSet
    name: calico-node
    namespace: kube-system
