resources:
- all.yaml
patches:
- path: ./patches/1706074730_remediate_SecurityContext_allowPrivilegeEscalation_for_workload_sock-shop-orders.yaml
  target:
    kind: Deployment
    namespace: sock-shop
