apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: istio-flasknginx
    tier: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: istio-flasknginx
      tier: nginx
  template:
    metadata:
      labels:
        app: istio-flasknginx
        tier: nginx
    spec:
      containers:
      - name: nginx-frontend
        image: {{ include "istio-flasknginx.nginx.image" . }}
        ports:
        - containerPort: 80
