---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: voter
  labels:
    name: voter-deployment
    app: nginxflask
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voter
      role: voterapp
      app: nginxflask
  template:
    spec:
      containers:
      - name: voter
        image: {{ include "istio-flasknginx.loadgen.image" . }}
        env:
        - name: URL
          value: nginx
        - name: SLEEPTIME
          value: "10"
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 32Mi
    metadata:
      labels:
        name: voter
        role: voterapp
        app: nginxflask

