resources:
- all.yaml
patches:
- path: ./patches/1704867285_remediate_SecurityContext_readOnlyRootFilesystem_for_workload_flask-greenversion.yaml
  target:
    kind: Deployment
    namespace: istio-flasknginx
