---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "grafana-sysdig.fullname" . }}
  name: {{ include "grafana-sysdig.fullname" . }}
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
        {{- include "grafana-sysdig.selectorLabels" . | nindent 6 }}
